coverage:
  ignore:
    - "*/tests/*"
    - qcelemental/_version.py
    - setup.py
  status:
    patch: false
    project:
      default:
        threshold: 80%
comment:
  layout: "header"
  require_changes: false
  branches: null
  behavior: once
